CONSTS = {
'RESTAURANT_CAMPAIGN' : (
    "Indulge in culinary delights at our restaurant's exclusive tasting event.",
    "Experience the flavors of our new seasonal menu, launching soon!",
    "Join us for a delightful evening of live music and gourmet cuisine.",
    "Dine with us and receive a complimentary appetizer on weekdays.",
    "Discover the art of fine dining at our elegant restaurant.",
    "Bring a friend and enjoy a 2-for-1 dining special this week.",
    "Treat yourself to a gastronomic journey with our chef's tasting menu.",
    "Follow us on social media for exclusive discounts and giveaways.",
    "Party with us and enjoy a special discount on group reservations.",
    "Celebrate your special occasion with personalized catering.",
    "Join our loyalty program and earn rewards with every visit.",
    "Experience our restaurant's farm-to-table concept, showcasing local ingredients.",
    "Visit our restaurant for a chance to win a luxurious culinary vacation.",
    "Indulge in our Sunday brunch buffet, featuring an array of delicacies.",
    "Book a private dining experience and enjoy personalized service.",
    "Enjoy our signature cocktails during happy hour, half-priced for all.",
    "Taste the essence of Italy with our authentic regional cuisine.",
    "Discover our secret recipes through our exclusive cookbook.",
    "Savor the flavors of the sea with our seafood-themed tasting menu.",
    "Experience a fusion of culinary traditions at our global cuisine festival.",
    "Savor the rich flavors of our signature steak cooked to perfection.",
    "Indulge in our mouthwatering lobster bisque for a taste of luxury.",
    "Experience a burst of freshness with our refreshing seasonal salads.",
    "Treat your senses to the exotic spices of our Thai curry dishes.",
    "Delight in the melt-in-your-mouth texture of our famous chocolate mousse.",
    "Enjoy a guilt-free meal with our selection of healthy and nutritious options.",
    "Immerse yourself in the vibrant colors and tastes of our sushi rolls.",
    "Elevate your dining experience with our expertly crafted cocktail pairings.",
    "Unlock a world of flavors with our globally inspired culinary creations.",
    "Experience the perfect harmony of sweet and savory in our applewood-smoked bacon.",
    "Awaken your taste buds with the zesty kick of our citrus-infused salmon.",
    "Discover the art of minimalism with our elegantly plated dishes.",
    "Feast on our bountiful seafood platter, featuring the catch of the day.",
    "Embark on a culinary adventure with our chef's special tasting menu.",
    "Unwind and relax with a fine glass of wine from our extensive collection.",
    "Celebrate the joy of togetherness with our family-style sharing plates.",
    "Dive into our cheesy lasagna for the ultimate comfort food experience.",
    "Satiate your cravings with our mouthwatering selection of gourmet burgers.",
    "Elevate your brunch game with our delectable avocado toast and poached eggs.",
    "Experience the perfect symphony of flavors in our fusion-inspired dishes.",
    "Unleash your inner foodie with our interactive DIY build-your-own pizza.",
    "Delight in the velvety smoothness of our handcrafted artisanal ice cream.",
    "Let our expert sommelier guide you through a wine-tasting journey.",
    "Experience the rustic charm and warmth of our wood-fired pizza oven.",
    "Ignite your taste buds with our fiery and flavorful Mexican street tacos.",
    "Experience a tantalizing blend of spices in our fragrant Indian curry.",
    "Satisfy your sweet tooth with our indulgent and decadent dessert platter.",
    "Delight in the delicate balance of flavors in our signature sushi rolls.",
    "Capture the essence of summer with our refreshing watermelon and feta salad.",
    "Embark on a culinary voyage through our seasonal farm-to-table menu.",
    "Unwind in our cozy lounge area and sip on artisanal handcrafted cocktails.",
    "Experience the tangy and aromatic explosion of our citrus-marinated chicken.",
    "Delight in the crisp and flaky exterior of our freshly baked croissants.",
    "Immerse yourself in the opulence of our black truffle-infused risotto.",
    "Treat yourself like royalty with our lavish and indulgent high tea service.",
    "Discover the secret behind our coveted secret recipe cheesecake.",
    "Elevate your coffee experience with our hand-roasted specialty brews.",
    "Immerse yourself in the rich and smoky flavors of our slow-cooked BBQ ribs.",
    "Satisfy your hunger with our generous portions of classic comfort food.",
    "Celebrate the season with our festive and colorful holiday-themed menu.",
    "Fall in love with the delicate aromas and flavors of our handmade pasta.",
    "Enjoy the perfect balance of sweet and tangy in our homemade lemon bars.",
    "Uncover a world of umami with our expertly prepared miso-glazed salmon.",
    "Savor the rich and velvety texture of our house-made butternut squash soup.",
    "Indulge in our sinfully decadent chocolate lava cake with a molten center.",
    "Immerse yourself in the fragrant and aromatic spices of our Moroccan tagine.",
    "Discover the layers of flavor in our meticulously prepared seven-course tasting menu.",
    "Ignite your senses with our fiery and flavorful buffalo chicken wings.",
    "Open the door to gastronomic paradise with our carefully curated international buffet.",
    "Delight in the smoky and tender perfection of our slow-roasted pulled pork.",
    "Experience the perfect fusion of East meets West in our teriyaki salmon.",
    "Unwind and relax in our cozy outdoor patio while enjoying stunning city views."
)
}